# Generated by Django 6.0.2 on 2026-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0012_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Image',
            field=models.CharField(default='images/default.jpg', max_length=100),
        ),
    ]
